package statuses

const (
	// Continue ...
	Continue = 100
	// SwitchingProtocols ...
	SwitchingProtocols = 101
	// Processing ...
	Processing = 102
)

const (
	// OK ...
	OK = 200
	// Created ...
	Created = 201
	// Accepted ...
	Accepted = 202
	// NonAuthoritativeInformation ...
	NonAuthoritativeInformation = 203
	// NoContent ...
	NoContent = 204
	// ResetContent ...
	ResetContent = 205
	// PartialContent ...
	PartialContent = 206
)

const (
	// MultipleChoices ...
	MultipleChoices = 300
	// MovedPermanently ...
	MovedPermanently = 301
	// Found ...
	Found = 302
	// SeeOther ...
	SeeOther = 303
	// NotModified ...
	NotModified = 304
	// UseProxy ...
	UseProxy = 305
	// SwitchProxy ...
	SwitchProxy = 306
	// TemporaryRedirect ...
	TemporaryRedirect = 307
	// PermanentRedirect ...
	PermanentRedirect = 308
)

const (
	// BadRequest ...
	BadRequest = 400
	// Unauthorized ...
	Unauthorized = 401
	// PaymentRequired ...
	PaymentRequired = 402
	// Forbidden ...
	Forbidden = 403
	// NotFound ...
	NotFound = 404
	// MethodNotAllowed ...
	MethodNotAllowed = 405
	// NotAcceptable ...
	NotAcceptable = 406
	// RequestTimeout ...
	RequestTimeout = 408
	// Conflict ...
	Conflict = 409
	// Gone ...
	Gone = 410
	// LengthRequired ...
	LengthRequired = 411
	// PreconditionFailed ...
	PreconditionFailed = 412
	// RequestEntityTooLarge ...
	RequestEntityTooLarge = 413
	// RequestURITooLong ...
	RequestURITooLong = 414
	// UnsupportedMediaType ...
	UnsupportedMediaType = 415
	// RequestedRangeNotSatisfiable ...
	RequestedRangeNotSatisfiable = 416
	// ExpectationFailed ...
	ExpectationFailed = 417
)

const (
	// InternalServerError ...
	InternalServerError = 500
	// NotImplemented ...
	NotImplemented = 501
	// BadGateway ...
	BadGateway = 502
	// ServiceUnavailable ...
	ServiceUnavailable = 503
	// GatewayTimeout ...
	GatewayTimeout = 504
	// HTTPVersionNotSupported ...
	HTTPVersionNotSupported = 505
	// VariantAlsoNegotiates ...
	VariantAlsoNegotiates = 506
	// InsufficientStorage ...
	InsufficientStorage = 507
	// LoopDetected ...
	LoopDetected = 508
	// BandwidthLimitExceeded ...
	BandwidthLimitExceeded = 509
	// NotExtended ...
	NotExtended = 510
	// NetworkAuthenticationRequired ...
	NetworkAuthenticationRequired = 511
	// OriginError ...
	OriginError = 520
	// WebServerIsDown ...
	WebServerIsDown = 521
	// ConnectionTimedOut ...
	ConnectionTimedOut = 522
	// ProxyDeclinedRequest ...
	ProxyDeclinedRequest = 523
	// TimeoutOccurred ...
	TimeoutOccurred = 524
	// NetworkReadTimeoutError ...
	NetworkReadTimeoutError = 598
	// NetworkConnectTimeoutError ...
	NetworkConnectTimeoutError = 599
)
